# Generated by Django 5.2.16 on 2026-07-19 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64)),
                ('fen', models.CharField(max_length=100)),
                ('move_no', models.PositiveIntegerField(blank=True, null=True)),
                ('eval_text', models.CharField(max_length=255)),
                ('eval_cp', models.FloatField(blank=True, null=True)),
                ('best_move_san', models.CharField(blank=True, max_length=16, null=True)),
                ('best_move_uci', models.CharField(blank=True, max_length=10, null=True)),
                ('analysis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_no', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game_id', 'fen'), name='uniq_user_game_fen')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True)),
                ('white_name', models.CharField(blank=True, max_length=255)),
                ('black_name', models.CharField(blank=True, max_length=255)),
                ('white_rating', models.CharField(blank=True, max_length=16)),
                ('black_rating', models.CharField(blank=True, max_length=16)),
                ('time_class', models.CharField(blank=True, max_length=32)),
                ('pgn', models.TextField(blank=True)),
                ('fen', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game_id'), name='uniq_user_game')],
            },
        ),
    ]
