# Generated by Django 5.2.16 on 2026-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0002_coachsuggestion_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='coachsuggestion',
            name='eval_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
