# Generated by Django 5.2.16 on 2026-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0002_coachsuggestion_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='analysis_enqueued_fen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_active', 'analysis_enqueued_fen', 'updated_at'], name='chessdotcom_is_acti_643297_idx'),
        ),
    ]
