# Generated by Django 6.0.7 on 2026-07-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0002_coachsuggestion_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis_enqueued_fen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
