# Generated by Django 5.2.16 on 2026-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chessdotcom_ai_coach", "0004_game_result_game_result_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachsuggestion",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
