# Generated by Django 5.2.16 on 2026-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0005_coachsuggestion_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
