# Generated by Django 5.2.16 on 2026-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessdotcom_ai_coach', '0007_alter_game_options_game_end_time_archiveimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
